#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./AllCreateParametersFiles

restore0Dir

runApplication setFields

runApplication decomposePar

runParallel renumberMesh -overwrite

runParallel $(getApplication)

runApplication reconstructPar

runApplication -s yPlus interFoam -postProcess -func yPlus
#------------------------------------------------------------------------------
