#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# Call automateParaView.py
# "c:/Program Files/ParaView 5.11.1/bin/pvpython.exe" automateParaview.py hullDTC.stl 0.244
# /usr/bin/pvpython automateParaview.py hullDTC.stl 0.244

# Call automateBlender.py
# Obtain length and beam from bounding box
# python3 automateBlender.py --stl_filepath hullDTC.stl --draft 0.244 --rho_water 1000
# python3 automateBlender.py --stl_filepath jbc.stl --draft 0.244 --rho_water 1000
# make sure to use the correct python version for bpy

# python3 IGStoSTL.py dtc.igs --scale 1
# python3 STLSurfaceToSolid.py hull_surface.stl

# Create variables
hull="w3.stl" # preprocessed watertight solid hull
draft=0.0928 # 0.0928 for ori
rho_water=997

# python3 blenderHullProperties.py hullDTC.stl --draft 0.244 --rho_water 1000
python3 blenderHullProperties.py $hull --draft $draft --rho_water $rho_water

#------------------------------------------------------------------------------
# sudo update-alternatives --config python3