#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# create foam file for Paraview
touch case.foam

# copy DTC hull STL to triSurface folder
mkdir -p constant/triSurface
cp hull.stl.gz constant/triSurface/

# Generate hull.eMesh file (edge features)
runApplication surfaceFeatureExtract

runApplication blockMesh # z-dir refinement

# Refinement in x and y dir only
for i in 1 2 3 4 5 #6
do
    runApplication -s $i \
        foamDictionary  system/refineMeshDict -entry set -set c${i}

    runApplication -s $i \
        topoSet -dict system/topoSetDict

    runApplication -s $i \
        refineMesh -dict system/refineMeshDict -overwrite
done

# Refinement in all 3 directions
for i in 6
do
    runApplication -s $i \
        foamDictionary  system/refineMeshDict3D -entry set -set c${i}

    runApplication -s $i \
        topoSet -dict system/topoSetDict

    runApplication -s $i \
        refineMesh -dict system/refineMeshDict3D -overwrite
done

runApplication -s forSnappyHexMesh decomposePar # decompose to run snappyHexMesh in parallel
runParallel snappyHexMesh -overwrite
# runApplication snappyHexMesh -overwrite

runParallel redistributePar -reconstruct -constant -overwrite # (not work in OF10)

rm -rf processor* # clean decomposed mesh not to interfere with interFoam decomposition

runApplication checkMesh -allGeometry -allTopology -writeAllFields -writeSets vtk

./AllCreateParametersFiles
#------------------------------------------------------------------------------
